controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']

admin_application_job_cv:
    path: /admin/application-job/{id}/cv
    controller: App\Controller\Admin\ApplicationJobCrudController::downloadCv
    methods: [GET]
