# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        application_job_cv:
            uri_prefix: /uploads/cvs
            upload_destination: '%kernel.project_dir%/public/uploads/cvs'
